name: Code Quality

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.4"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
            eval `ssh-agent -s`
            ssh-add - <<< '${{ secrets.SHIMMER_DEPLOY }}'
            poetry install --with dev
      - uses: isort/isort-action@master
        with:
            configuration: "--profile=black --check-only --diff --py=311"
            sort-paths: "simple_shapes_dataset playground"
      - uses: psf/black@stable
        with:
          src: "."
      - name: Analysing the code with flake8
        run: |
          poetry run flake8 .
      - name: Analysing the code with mypy
        run: |
          poetry run mypy --install-types --non-interactive .
